image: node:9.4

cache:
  paths:
  - node_modules/

before_script:
  - uname -v
  - python -V
  # note: yarn is included in the image, so we don't need to install it
  - apt-get update && apt-get -y upgrade
  - apt-get install -y xvfb
  # electron required dependency; see https://electronjs.org/docs/development/build-instructions-linux
  - apt-get install -y libgtk2.0-dev
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn
  
stages:
  - build
  
build_test:
  stage: build
  script:
    - yarn test
    - yarn start
    - yarn run build-linux
    - ls dist
  