image: node:9.4

cache:
  paths:
  - node_modules/

before_script:
  - uname -v
  - python -V
  # note: yarn is included in the image, so we don't need to install it
  # electron required dependencies; see https://electronjs.org/docs/development/build-instructions-linux
  - apt-get -qq update && apt-get install -qq -y \
                                                 build-essential \
                                                 clang \
                                                 libdbus-1-dev \
                                                 libgtk2.0-dev \
                                                 libnotify-dev \
                                                 libgnome-keyring-dev \
                                                 libgconf2-dev \
                                                 libasound2-dev \
                                                 libcap-dev \
                                                 libcups2-dev \
                                                 libxtst-dev \
                                                 libxss1 \
                                                 libnss3-dev \
                                                 gcc-multilib \
                                                 g++-multilib \
                                                 curl \
                                                 gperf \
                                                 bison \
                                                 xvfb
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn
  
stages:
  - build
  
build_test:
  stage: build
  script:
    - yarn test
    - yarn start
    - yarn run build-linux
    - ls dist
  