version: 0.3.0.{build}

cache:
  - node_modules

environment:
  GH_TOKEN:
    secure: 25lIq5iUz6o1FTDxaMPXz0B9dwJm7bPxiC3+ALhnLP1lB1vWZBi3oqn0OCDom/3a

install:
  - ps: Install-Product node $env:9
  - yarn

build: off

test_script:
  - node --version
  - yarn --version
  - yarn test
  - yarn run build-win64

shallow_clone: true
clone_depth: 1
