version: 0.2.0

install:
  - ps: Install-Product node $env:9
  - yarn

build: off
build_script:
  - yarn test
  - yarn run build-win64

test_script:
  - node --version
  - yarn --version
  - yarn test

artifacts:
  - path: 'dist\Vatron Setup %APPVEYOR_BUILD_VERSION%.exe'
    name: squirrel

  - path: 'dist\VatronInstaller.%APPVEYOR_BUILD_VERSION%.exe'
    name: installer

  - path: 'dist\VatronPortable.%APPVEYOR_BUILD_VERSION%.exe',
    name: portable

deploy:
- provider: GitHub
  auth_token:
    secure: ciXMGY38RIpZz85UAe8Hnddb/mMk4yj+lFo5pYd0RUYG461FJdBjSHiCiyw+8OD2
  artifact: squirrel,installer,portable
  draft: true
