version: 0.3.0.{build}

install:
  - ps: Install-Product node $env:9
  - yarn

build: off
build_script:
  - yarn test
  - yarn run build-win64
  - ps: rd -r "dist\win-unpacked"

test_script:
  - node --version
  - yarn --version
  - yarn test

artifacts:
  - path: 'dist/squirrel-windows/VatronSquirrel.exe'
    name: squirrel

  - path: 'dist/VatronPortable.exe'
    name: portable
